---
title: HealthCare.gov Styleguide
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
canonical-url: http://styleguide.healthcare.gov
permalink: "/:categories/:title/"
markdown: kramdown
highlighter: 
encoding: utf-8
exclude:
- ".gitignore"
- README.md
- privatekey.p12
- Gemfile
- Gemfile.lock
- node_modules
- ".gitattributes"
- Gruntfile.js
- package.json
languages:
- name: English
  value: en
- name: Español
  value: es
